version: 0.2

phases:
  install:
    runtime-versions:
    commands:
  build:
    commands:
      - ./mvnw clean install
env:
  variables:
    FLYWAY_URL: jdbc:mysql://localhost:3306/aws-codepipeline
    FLYWAY_USER: root
    FLYWAY_PASSWORD: Deep@#1234
